In [1]:
import pandas as pd
import numpy as np
import math
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
import os
#path = "E:"
#os.chdir(path)

In [2]:
def create_dataset_train(dataset, TarY, look_back):
    dataX, dataY = [], []
    for i in range(len(dataset)-look_back):
        toTrain = dataset[i:(i+look_back), :]
        dataX.append(toTrain)
        toTarY = TarY[i+look_back] ### Y is a single value
        dataY.append(toTarY)
    return np.array(dataX), np.array(dataY)

In [3]:
def create_dataset(dataset, TarY, look_back):
    dataX, dataY = [], []
    for i in range(len(dataset)-look_back):
        toTrain = dataset[i:(i+look_back)]
        dataX.append(toTrain)
        toTarY = TarY[i+look_back] ### Y is a single value
        dataY.append(toTarY)
    return np.array(dataX), np.array(dataY)

In [4]:
#df = pd.read_csv("E:\\key_table_save_reddoor_v2.txt", sep="\t")
#leadingW_mx_df = pd.read_csv("E:\\leadingW_reddoor_v2.txt", sep="\t")

df = pd.read_csv("ts/key_table_20180116_term500_10000000.txt", sep="\t")
leadingW_mx_df = pd.read_csv("ts/leadingW_20180116_term500_10000000.txt", sep="\t")

In [5]:
'''
df = pd.read_csv("ts/key_table_save_prod_effects1229_v2.txt", sep="\t")
leadingW_mx_df = pd.read_csv("ts/leadingWeight_prod_effects1229.txt", sep="\t")
'''

'\ndf = pd.read_csv("ts/key_table_save_prod_effects1229_v2.txt", sep="\t")\nleadingW_mx_df = pd.read_csv("ts/leadingWeight_prod_effects1229.txt", sep="\t")\n'

In [6]:
leadingW_mx_df

0    1    2    3    4    5    6    7    8    9 ...   381  382  383  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
5    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
6    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
7    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
8    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
9    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
10   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
11   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
12   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
13   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
14   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
15   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
16   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
17   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
18   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
19   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
20   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
21   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
22   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
23   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
24   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
25   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
26   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
27   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
28   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
29   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...   
361  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
362  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
363  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
364  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
365  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
366  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
367  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
368  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
369  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
370  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
371  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
372  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
373  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
374  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
375  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
376  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
377  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
378  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
379  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
380  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
381

In [158]:
leadingW_mx_np = np.array(leadingW_mx_df)
MA_ts_np = np.array(df)

col_end = MA_ts_np.shape[1] + 1
row_end = MA_ts_np.shape[0] + 1
look_back =5
look_back_test = look_back-1
look_ahead_test = 1
train_test_ratio = 0.95 ### if it is set to 0.8, it means for training: 0.8, for testing: 0.2
train_row_end = int(MA_ts_np.shape[0] * train_test_ratio + 0.5)
pred_size =  MA_ts_np.shape[0] - train_row_end 
ctrl_val = row_end - 1 ### total prediction time point in testing

### initialize the result matrix
col_pointer = 0
pred_ts_dataMX = pd.DataFrame(MA_ts_np[0:pred_size,col_pointer]).rename(columns = {0:list(df)[col_pointer]})
dataset = df.values

In [159]:
train_row_end,ctrl_val

(24, 25)

In [160]:
trainX[-5:,:]

array([[   441.,   8460.,  13500.,   9540.,   7750.],
       [  8460.,  13500.,   9540.,   7750.,   4500.],
       [ 13500.,   9540.,   7750.,   4500.,   1890.],
       [  9540.,   7750.,   4500.,   1890.,   1360.],
       [  7750.,   4500.,   1890.,   1360.,   1030.]], dtype=float32)

In [161]:
test[:]

array([ 4500.,  1890.,  1360.,  1030.,   997.], dtype=float32)

In [162]:
### proposed method: leading factors pred target ts
### including self prediction if threre is no leading ts for target ts
### pred t+1 step by step

for j in range(col_pointer,leadingW_mx_np.shape[1]):
        MA_ts_data = pd.DataFrame(MA_ts_np[:,j]).rename(columns = {0:list(df)[j]})               
        pd_tmp = pd.DataFrame(MA_ts_np[0:pred_size,j]) ### given tmp value
        for mv in range(train_row_end, ctrl_val): ### varied 'train_row_end'
            print('mv',mv)
            dataset = MA_ts_data.values
            dataset2 = dataset[0:mv+1,0].astype('float32') # for training
            dataset3 = dataset[mv-look_back_test:mv+look_ahead_test,0].astype('float32') # for testing            
            trainTarY = dataset[0:mv+1,0]
            testTarY = dataset[mv+1:ctrl_val,0]
            
            train = dataset2
            test = dataset3

            trainX, trainY = create_dataset(train,trainTarY, look_back)
            print('trainX:',trainX,'trainY', trainY)
            
            reg = linear_model.LinearRegression()   
            reg.fit(list(trainX[:,:]),list(trainY[:]))
            model_Pred_result= reg.predict(test)
            print('test:',test)
            pd_tmp.iloc[mv-train_row_end] = model_Pred_result
        pred_ts_dataMX[list(df)[j]] = pd_tmp
        pred_ts_dataMX.to_csv('Regression_self_1124.txt', sep='\t', index=0, header = 1, encoding = 'utf8')


mv 24
trainX: [[  935.  1060.  1100.  1200.    91.]
 [ 1060.  1100.  1200.    91.  1420.]
 [ 1100.  1200.    91.  1420.  1640.]
 [ 1200.    91.  1420.  1640.  1910.]
 [   91.  1420.  1640.  1910.  1680.]
 [ 1420.  1640.  1910.  1680.  1390.]
 [ 1640.  1910.  1680.  1390.  1480.]
 [ 1910.  1680.  1390.  1480.  2470.]
 [ 1680.  1390.  1480.  2470.  2780.]
 [ 1390.  1480.  2470.  2780.  2460.]
 [ 1480.  2470.  2780.  2460.  2410.]
 [ 2470.  2780.  2460.  2410.  2220.]
 [ 2780.  2460.  2410.  2220.  2170.]
 [ 2460.  2410.  2220.  2170.   116.]
 [ 2410.  2220.  2170.   116.  2380.]
 [ 2220.  2170.   116.  2380.  3350.]
 [ 2170.   116.  2380.  3350.  3960.]
 [  116.  2380.  3350.  3960.  3440.]
 [ 2380.  3350.  3960.  3440.  3740.]
 [ 3350.  3960.  3440.  3740.  3880.]] trainY [1420 1640 1910 1680 1390 1480 2470 2780 2460 2410 2220 2170  116 2380 3350
 3960 3440 3740 3880 4720]
test: [ 3960.  3440.  3740.  3880.  4720.]
mv 24
trainX: [[  3.00000000e+00   2.28000000e+04   2.28000000e+04   2.2

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

trainX: [[    52.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]
 [ 15900.  15900.  15900.  15900.  15900.]] trainY [15900 15900 15900 15900 15900 15900 15900 15900 15900 15900 15900 15900
 15900 15900 15900 15900 15900 15900 15900 15900]
t

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

mv 24
trainX: [[  755.   723.  1040.  1280.  1060.]
 [  723.  1040.  1280.  1060.  1130.]
 [ 1040.  1280.  1060.  1130.  1230.]
 [ 1280.  1060.  1130.  1230.  1180.]
 [ 1060.  1130.  1230.  1180.  1250.]
 [ 1130.  1230.  1180.  1250.  1250.]
 [ 1230.  1180.  1250.  1250.  1280.]
 [ 1180.  1250.  1250.  1280.  1420.]
 [ 1250.  1250.  1280.  1420.  2590.]
 [ 1250.  1280.  1420.  2590.  2700.]
 [ 1280.  1420.  2590.  2700.  1790.]
 [ 1420.  2590.  2700.  1790.  1740.]
 [ 2590.  2700.  1790.  1740.  1680.]
 [ 2700.  1790.  1740.  1680.  1870.]
 [ 1790.  1740.  1680.  1870.  2040.]
 [ 1740.  1680.  1870.  2040.  2960.]
 [ 1680.  1870.  2040.  2960.  3470.]
 [ 1870.  2040.  2960.  3470.  2980.]
 [ 2040.  2960.  3470.  2980.  2850.]
 [ 2960.  3470.  2980.  2850.  2980.]] trainY [1130 1230 1180 1250 1250 1280 1420 2590 2700 1790 1740 1680 1870 2040 2960
 3470 2980 2850 2980 3040]
test: [ 3470.  2980.  2850.  2980.  3040.]
mv 24
trainX: [[  2370.   2200.   1860.   1860.   1870.]
 [  2200.   186

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

test: [ 1500.  1260.  3260.  4030.  3990.]
mv 24
trainX: [[  657.   421.   419.   450.   391.]
 [  421.   419.   450.   391.   519.]
 [  419.   450.   391.   519.   759.]
 [  450.   391.   519.   759.   747.]
 [  391.   519.   759.   747.   674.]
 [  519.   759.   747.   674.   669.]
 [  759.   747.   674.   669.  3560.]
 [  747.   674.   669.  3560.  3820.]
 [  674.   669.  3560.  3820.  1140.]
 [  669.  3560.  3820.  1140.  1640.]
 [ 3560.  3820.  1140.  1640.  1800.]
 [ 3820.  1140.  1640.  1800.  1300.]
 [ 1140.  1640.  1800.  1300.  1280.]
 [ 1640.  1800.  1300.  1280.  1540.]
 [ 1800.  1300.  1280.  1540.  1520.]
 [ 1300.  1280.  1540.  1520.  1720.]
 [ 1280.  1540.  1520.  1720.  1830.]
 [ 1540.  1520.  1720.  1830.  1600.]
 [ 1520.  1720.  1830.  1600.  3580.]
 [ 1720.  1830.  1600.  3580.  4340.]] trainY [ 519  759  747  674  669 3560 3820 1140 1640 1800 1300 1280 1540 1520 1720
 1830 1600 3580 4340 4320]
test: [ 1830.  1600.  3580.  4340.  4320.]
mv 24
trainX: [[  753.   628.

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

mv 24
trainX: [[  540.   451.   496.   566.   561.]
 [  451.   496.   566.   561.   751.]
 [  496.   566.   561.   751.   992.]
 [  566.   561.   751.   992.  1020.]
 [  561.   751.   992.  1020.   909.]
 [  751.   992.  1020.   909.   966.]
 [  992.  1020.   909.   966.  1220.]
 [ 1020.   909.   966.  1220.  1450.]
 [  909.   966.  1220.  1450.  3020.]
 [  966.  1220.  1450.  3020.  3750.]
 [ 1220.  1450.  3020.  3750.  2460.]
 [ 1450.  3020.  3750.  2460.  1880.]
 [ 3020.  3750.  2460.  1880.  1880.]
 [ 3750.  2460.  1880.  1880.  2030.]
 [ 2460.  1880.  1880.  2030.  2240.]
 [ 1880.  1880.  2030.  2240.  3070.]
 [ 1880.  2030.  2240.  3070.  3530.]
 [ 2030.  2240.  3070.  3530.  3110.]
 [ 2240.  3070.  3530.  3110.  2800.]
 [ 3070.  3530.  3110.  2800.  2550.]] trainY [ 751  992 1020  909  966 1220 1450 3020 3750 2460 1880 1880 2030 2240 3070
 3530 3110 2800 2550 2980]
test: [ 3530.  3110.  2800.  2550.  2980.]
mv 24
trainX: [[   473.    480.    487.    747.   1810.]
 [   480.    48

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

mv 24
trainX: [[ 2690.  2870.  3440.  3480.  2850.]
 [ 2870.  3440.  3480.  2850.  2750.]
 [ 3440.  3480.  2850.  2750.  3690.]
 [ 3480.  2850.  2750.  3690.  3900.]
 [ 2850.  2750.  3690.  3900.  5010.]
 [ 2750.  3690.  3900.  5010.  5300.]
 [ 3690.  3900.  5010.  5300.  9710.]
 [ 3900.  5010.  5300.  9710.  9660.]
 [ 5010.  5300.  9710.  9660.  4970.]
 [ 5300.  9710.  9660.  4970.  5250.]
 [ 9710.  9660.  4970.  5250.  5150.]
 [ 9660.  4970.  5250.  5150.  5240.]
 [ 4970.  5250.  5150.  5240.  5060.]
 [ 5250.  5150.  5240.  5060.  6130.]
 [ 5150.  5240.  5060.  6130.  6120.]
 [ 5240.  5060.  6130.  6120.  8380.]
 [ 5060.  6130.  6120.  8380.  9610.]
 [ 6130.  6120.  8380.  9610.  7620.]
 [ 6120.  8380.  9610.  7620.  7690.]
 [ 8380.  9610.  7620.  7690.  8390.]] trainY [2750 3690 3900 5010 5300 9710 9660 4970 5250 5150 5240 5060 6130 6120 8380
 9610 7620 7690 8390 9910]
test: [ 9610.  7620.  7690.  8390.  9910.]
mv 24
trainX: [[  181.   218.   245.   263.   535.]
 [  218.   245.   26

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

mv 24
trainX: [[ 250.  323.  411.  455.  437.]
 [ 323.  411.  455.  437.  571.]
 [ 411.  455.  437.  571.  711.]
 [ 455.  437.  571.  711.  676.]
 [ 437.  571.  711.  676.  589.]
 [ 571.  711.  676.  589.  492.]
 [ 711.  676.  589.  492.  400.]
 [ 676.  589.  492.  400.  444.]
 [ 589.  492.  400.  444.  542.]
 [ 492.  400.  444.  542.  554.]
 [ 400.  444.  542.  554.  507.]
 [ 444.  542.  554.  507.  621.]
 [ 542.  554.  507.  621.  611.]
 [ 554.  507.  621.  611.  585.]
 [ 507.  621.  611.  585.  586.]
 [ 621.  611.  585.  586.  738.]
 [ 611.  585.  586.  738.  800.]
 [ 585.  586.  738.  800.  680.]
 [ 586.  738.  800.  680.  610.]
 [ 738.  800.  680.  610.  932.]] trainY [ 571  711  676  589  492  400  444  542  554  507  621  611  585  586  738
  800  680  610  932 1080]
test: [  800.   680.   610.   932.  1080.]
mv 24
trainX: [[  451.   497.   509.   508.   491.]
 [  497.   509.   508.   491.   586.]
 [  509.   508.   491.   586.   665.]
 [  508.   491.   586.   665.   644.]
 [  49

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

mv 24
trainX: [[  413.   449.   490.   446.   413.]
 [  449.   490.   446.   413.   410.]
 [  490.   446.   413.   410.   470.]
 [  446.   413.   410.   470.   558.]
 [  413.   410.   470.   558.   581.]
 [  410.   470.   558.   581.   510.]
 [  470.   558.   581.   510.   493.]
 [  558.   581.   510.   493.   576.]
 [  581.   510.   493.   576.  1620.]
 [  510.   493.   576.  1620.  1690.]
 [  493.   576.  1620.  1690.   845.]
 [  576.  1620.  1690.   845.   800.]
 [ 1620.  1690.   845.   800.   813.]
 [ 1690.   845.   800.   813.   811.]
 [  845.   800.   813.   811.   826.]
 [  800.   813.   811.   826.  1620.]
 [  813.   811.   826.  1620.  1860.]
 [  811.   826.  1620.  1860.  1250.]
 [  826.  1620.  1860.  1250.  1370.]
 [ 1620.  1860.  1250.  1370.  1520.]] trainY [ 410  470  558  581  510  493  576 1620 1690  845  800  813  811  826 1620
 1860 1250 1370 1520 1260]
test: [ 1860.  1250.  1370.  1520.  1260.]
mv 24
trainX: [[ 1110.  1100.  1260.  1420.  1460.]
 [ 1100.  1260.  142

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

mv 24
trainX: [[  408.   379.   441.   489.   520.]
 [  379.   441.   489.   520.   580.]
 [  441.   489.   520.   580.   692.]
 [  489.   520.   580.   692.   680.]
 [  520.   580.   692.   680.   702.]
 [  580.   692.   680.   702.   741.]
 [  692.   680.   702.   741.   750.]
 [  680.   702.   741.   750.   878.]
 [  702.   741.   750.   878.  2100.]
 [  741.   750.   878.  2100.  2220.]
 [  750.   878.  2100.  2220.  1310.]
 [  878.  2100.  2220.  1310.  1200.]
 [ 2100.  2220.  1310.  1200.  1010.]
 [ 2220.  1310.  1200.  1010.  1210.]
 [ 1310.  1200.  1010.  1210.  1420.]
 [ 1200.  1010.  1210.  1420.  1920.]
 [ 1010.  1210.  1420.  1920.  2250.]
 [ 1210.  1420.  1920.  2250.  1900.]
 [ 1420.  1920.  2250.  1900.  1720.]
 [ 1920.  2250.  1900.  1720.  1980.]] trainY [ 580  692  680  702  741  750  878 2100 2220 1310 1200 1010 1210 1420 1920
 2250 1900 1720 1980 2030]
test: [ 2250.  1900.  1720.  1980.  2030.]
mv 24
trainX: [[  916.   897.   866.   745.   763.]
 [  897.   866.   74

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

mv 24
trainX: [[  437.   378.   377.   496.   540.]
 [  378.   377.   496.   540.   503.]
 [  377.   496.   540.   503.   524.]
 [  496.   540.   503.   524.   617.]
 [  540.   503.   524.   617.   696.]
 [  503.   524.   617.   696.   796.]
 [  524.   617.   696.   796.   750.]
 [  617.   696.   796.   750.   755.]
 [  696.   796.   750.   755.  1070.]
 [  796.   750.   755.  1070.  1190.]
 [  750.   755.  1070.  1190.  1230.]
 [  755.  1070.  1190.  1230.  1440.]
 [ 1070.  1190.  1230.  1440.  1390.]
 [ 1190.  1230.  1440.  1390.  1700.]
 [ 1230.  1440.  1390.  1700.  1860.]
 [ 1440.  1390.  1700.  1860.  2200.]
 [ 1390.  1700.  1860.  2200.  2520.]
 [ 1700.  1860.  2200.  2520.  2010.]
 [ 1860.  2200.  2520.  2010.  1980.]
 [ 2200.  2520.  2010.  1980.  2530.]] trainY [ 503  524  617  696  796  750  755 1070 1190 1230 1440 1390 1700 1860 2200
 2520 2010 1980 2530 3400]
test: [ 2520.  2010.  1980.  2530.  3400.]
mv 24
trainX: [[  940.   828.   627.   650.   593.]
 [  828.   627.   65

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

mv 24
trainX: [[    48.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]
 [ 38000.  38000.  38000.  38000.  38000.]] trainY [38000 38000 38000 38000 38000 38000 38000 38000 38000 38000 38000 38000
 38000 38000 38000 38000 38000 38000 38000 38

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

test: [ 2060.  1620.  1650.  1810.  2290.]
mv 24
trainX: [[  589.   516.   635.   708.   666.]
 [  516.   635.   708.   666.   660.]
 [  635.   708.   666.   660.   708.]
 [  708.   666.   660.   708.   806.]
 [  666.   660.   708.   806.   853.]
 [  660.   708.   806.   853.   991.]
 [  708.   806.   853.   991.  1050.]
 [  806.   853.   991.  1050.  1150.]
 [  853.   991.  1050.  1150.  1560.]
 [  991.  1050.  1150.  1560.  1570.]
 [ 1050.  1150.  1560.  1570.  1290.]
 [ 1150.  1560.  1570.  1290.  1300.]
 [ 1560.  1570.  1290.  1300.  1300.]
 [ 1570.  1290.  1300.  1300.  1470.]
 [ 1290.  1300.  1300.  1470.  1620.]
 [ 1300.  1300.  1470.  1620.  2380.]
 [ 1300.  1470.  1620.  2380.  2680.]
 [ 1470.  1620.  2380.  2680.  2100.]
 [ 1620.  2380.  2680.  2100.  2120.]
 [ 2380.  2680.  2100.  2120.  2430.]] trainY [ 660  708  806  853  991 1050 1150 1560 1570 1290 1300 1300 1470 1620 2380
 2680 2100 2120 2430 3190]
test: [ 2680.  2100.  2120.  2430.  3190.]
mv 24
trainX: [[  545.   490.

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

mv 24
trainX: [[ 1130.  1100.  1350.  1420.  1200.]
 [ 1100.  1350.  1420.  1200.  1210.]
 [ 1350.  1420.  1200.  1210.  1320.]
 [ 1420.  1200.  1210.  1320.  1380.]
 [ 1200.  1210.  1320.  1380.  1500.]
 [ 1210.  1320.  1380.  1500.  1440.]
 [ 1320.  1380.  1500.  1440.  1280.]
 [ 1380.  1500.  1440.  1280.  1350.]
 [ 1500.  1440.  1280.  1350.  2660.]
 [ 1440.  1280.  1350.  2660.  2950.]
 [ 1280.  1350.  2660.  2950.  2000.]
 [ 1350.  2660.  2950.  2000.  1880.]
 [ 2660.  2950.  2000.  1880.  1910.]
 [ 2950.  2000.  1880.  1910.  2180.]
 [ 2000.  1880.  1910.  2180.  2070.]
 [ 1880.  1910.  2180.  2070.  3470.]
 [ 1910.  2180.  2070.  3470.  4110.]
 [ 2180.  2070.  3470.  4110.  2870.]
 [ 2070.  3470.  4110.  2870.  2730.]
 [ 3470.  4110.  2870.  2730.  3250.]] trainY [1210 1320 1380 1500 1440 1280 1350 2660 2950 2000 1880 1910 2180 2070 3470
 4110 2870 2730 3250 3980]
test: [ 4110.  2870.  2730.  3250.  3980.]
mv 24
trainX: [[  3710.   3690.   4190.   4450.   3930.]
 [  3690.   419

D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anaconda\envs\py3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
D:\Anac

In [163]:
pred_ts_dataMX.values[0],MA_ts_np[-1,:]

(array([   4466.23062129,   22800.        ,    9639.29542949,
          13876.68885591,    2035.09885713,  171245.19711773,
           9335.13217778,   17300.        ,    4077.58540373,
           4775.29028148,   38800.        ,    4215.48163974,
          13171.58367347,    4441.74711318,    2839.03675472,
           3404.34572825,   37846.25401391,    1412.44255577,
         111000.        ,    1664.27186336,    2795.71733205,
           3459.65766911,    3430.90612194,    4778.77340298,
           6146.83169451,    5464.70285431,    3461.35218179,
           8450.84977516,    2572.75061526,    2021.48359856,
          12099.16915707,    1330.25957043,    6058.63270717,
           7710.        ,    6875.43915294,   15900.        ,
           1546.62187055,    2737.38054625,    1636.67839357,
          28270.5899617 ,    8142.41526918,    1356.61905665,
           1707.29551579,    5885.48725595,   19690.40072303,
          10268.9937366 ,    4719.19727148,    7718.48586628,
        

In [164]:
del FP,FN,TN

In [165]:
#不考慮幅度
#this is for binary classification(只考慮上升下降.不考慮幅度)
def pred_updown(t,t1_pred,t1_true):
    
    global TP
    global FP
    global FN
    global TN

    if t>t1_pred:
        print('pred:-1')
        if t> t1_true:
            print('TN')
            TN+=1
        else :
            print('FN')
            FN+=1
    elif t==t1_pred:
        print('=')
        TP+=1
    else :
        print('pred:+1')
        if t< t1_true:
            print('TP')
            TP+=1
            print(TP)
          
        else :
            print('FP')
            FP+=1
TP=0
FP=0
FN=0
TN=0
for i in range(0,MA_ts_np.shape[1]):
    
    t=MA_ts_np[-2,i]#now
    t1_true=MA_ts_np[-1,i]
    t1_pred=pred_ts_dataMX.values[0][i]

    print(t,t1_true,t1_pred)
    if t> t1_true :
        print('true:-1')
        print('\t')
    
        pred_updown(t,t1_pred,t1_true)
    elif t== t1_true :
        print('=')
        print('\t')
        pred_updown(t,t1_pred,t1_true)
    else:
        print('true:+1')
        print('\t')
        pred_updown(t,t1_pred,t1_true)
print('TP:',TP,'FP:',FP,'FN:',FN,'TN:',TN)

3880 4720 4466.23062129
true:+1
	
pred:+1
TP
1
22800 22800 22800.0
=
	
=
7490 8960 9639.29542949
true:+1
	
pred:+1
TP
3
12100 14300 13876.6888559
true:+1
	
pred:+1
TP
4
1650 1900 2035.09885713
true:+1
	
pred:+1
TP
5
151000 157000 171245.197118
true:+1
	
pred:+1
TP
6
8330 8220 9335.13217778
true:-1
	
pred:+1
FP
17300 17300 17300.0
=
	
=
1970 2240 4077.58540373
true:+1
	
pred:+1
TP
8
3700 3290 4775.29028148
true:-1
	
pred:+1
FP
38800 38800 38800.0
=
	
=
3780 4570 4215.48163974
true:+1
	
pred:+1
TP
10
7690 10300 13171.5836735
true:+1
	
pred:+1
TP
11
3780 4170 4441.74711318
true:+1
	
pred:+1
TP
12
2140 2850 2839.03675472
true:+1
	
pred:+1
TP
13
2650 3310 3404.34572825
true:+1
	
pred:+1
TP
14
22600 24300 37846.2540139
true:+1
	
pred:+1
TP
15
1230 1350 1412.44255577
true:+1
	
pred:+1
TP
16
111000 111000 111000.0
=
	
=
1110 1410 1664.27186336
true:+1
	
pred:+1
TP
18
1810 2610 2795.71733205
true:+1
	
pred:+1
TP
19
2990 3220 3459.65766911
true:+1
	
pred:+1
TP
20
2900 3100 3430.90612194
true:+1


In [166]:
#考慮上升下降幅度 multi classification(1,0,-1)
TP=0
FP=0
FN=0
TN=0
true_upd_list=[]
pred_upd_list=[]
thresh=0.1
for i in range(0,MA_ts_np.shape[1]): 
    


    t=MA_ts_np[-2,i]#now
    t1_true_origin=MA_ts_np[-1,i]
    t1_pred_origin=pred_ts_dataMX.values[0][i]
    true_upd= (t1_true_origin-t)/t
    pred_upd= (t1_pred_origin-t)/t

    print( 'true:',true_upd,'pred:',pred_upd  )
    if true_upd >=thresh:

        #up

        if pred_upd>=thresh:
            true_upd_list.append(1)
            pred_upd_list.append(1)
            print('1,1')
            #TP+=1
        elif  pred_upd<=-thresh:
            true_upd_list.append(1)
            pred_upd_list.append(-1)
            print('1,-1')
            #FN+=1
        else:
            true_upd_list.append(1)
            pred_upd_list.append(0)
            print('1,0')

    elif true_upd<=-thresh:
        #down
        if pred_upd>=thresh:
            true_upd_list.append(-1)
            pred_upd_list.append(1)
            print('-1,1')
            #FP+=1
        elif  pred_upd<=-thresh:
            true_upd_list.append(-1)
            pred_upd_list.append(-1)
            print('-1,-1')
            #TN+=1
        else :
            true_upd_list.append(-1)
            pred_upd_list.append(0)
            print('-1,0')
    else:

        if pred_upd>=thresh:
            true_upd_list.append(0)
            pred_upd_list.append(1)
            print('0,1')
            #FP+=1
        elif  pred_upd<=-thresh:
            true_upd_list.append(0)
            pred_upd_list.append(-1)
            print('0,-1')
            #TN+=1
        else :
            true_upd_list.append(0)
            pred_upd_list.append(0)
            print('0,0')


true: 0.216494845361 pred: 0.151090366312
1,1
true: 0.0 pred: 0.0
0,0
true: 0.196261682243 pred: 0.28695533104
1,1
true: 0.181818181818 pred: 0.146833789745
1,1
true: 0.151515151515 pred: 0.233393246745
1,1
true: 0.0397350993377 pred: 0.134074153098
0,1
true: -0.0132052821128 pred: 0.120664126985
0,1
true: 0.0 pred: 0.0
0,0
true: 0.137055837563 pred: 1.06984030646
1,1
true: -0.110810810811 pred: 0.290618994995
-1,1
true: 0.0 pred: 0.0
0,0
true: 0.208994708995 pred: 0.115206783001
1,1
true: 0.339401820546 pred: 0.712819723468
1,1
true: 0.103174603175 pred: 0.175065373857
1,1
true: 0.331775700935 pred: 0.32665268912
1,1
true: 0.249056603774 pred: 0.284658765378
1,1
true: 0.0752212389381 pred: 0.674613009465
0,1
true: 0.0975609756098 pred: 0.148327281112
0,1
true: 0.0 pred: 0.0
0,0
true: 0.27027027027 pred: 0.499344021048
1,1
true: 0.441988950276 pred: 0.544595211076
1,1
true: 0.0769230769231 pred: 0.157076143517
0,1
true: 0.0689655172414 pred: 0.18307107653
0,1
true: 0.412844036697 pred:

In [171]:
from sklearn import metrics
print(metrics.precision_score(true_upd_list, pred_upd_list, average='macro'))
print(metrics.recall_score(true_upd_list, pred_upd_list, average='macro'))
print(metrics.f1_score(true_upd_list, pred_upd_list, average='micro'))


0.717404396266
0.50815696649
0.703324808184


In [172]:
from sklearn.metrics import mean_squared_error
from math import sqrt
y_predicted=pred_ts_dataMX.values[0]
y_actual=MA_ts_np[-1,:]
mse = sqrt(mean_squared_error(y_actual, y_predicted))

In [173]:
print('mse:',mse,'rmse:',mse**(.5))

mse: 4792.839768066512 rmse: 69.23033849452501
